### ISSUE TITLE
Multiline variables

### ISSUE THREAD

**Issue by gudjonragnar** [mre/envy#79]
I have a use case where I want to set an env variable like this:
```
FLINK_PROPERTIES="jobmanager.rpc.address: host
taskmanager.numberOfTaskSlots: 3
blob.server.port: 6124
"
```
I could not do that properly, do you have a solution to this?

**Comment by mre** [comment]
Since envy's config file is just TOML, you can use a multiline string like so I guess:

```toml
[[paths]]
pattern = ".*yourpattern.*"
env = [
  "foo=bar",
  '''
  FLINK_PROPERTIES="jobmanager.rpc.address: host
  taskmanager.numberOfTaskSlots: 3
  blob.server.port: 6124"
  ''',
]
```
